//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.09 at 03:53:07 PM EST 
//


package parser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="heartrate">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPErate">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanprint">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanqrsdur">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanqtint">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="meanqtc">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="i40frontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="t40frontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="qrsfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tfrontaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="phorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="i40horizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="t40horizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="qrshorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sthorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="thorizaxis">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
 *                 &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="arrhyflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="editedflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "heartrate",
    "rrint",
    "atrialrate",
    "pdur",
    "print",
    "qonset",
    "qrsdur",
    "qtint",
    "qtcb",
    "qtcf",
    "pfrontaxis",
    "i40frontaxis",
    "t40frontaxis",
    "qrsfrontaxis",
    "stfrontaxis",
    "tfrontaxis",
    "phorizaxis",
    "i40horizaxis",
    "t40horizaxis",
    "qrshorizaxis",
    "sthorizaxis",
    "thorizaxis"
})
@XmlRootElement(name = "interpretationmeasurements")
public class Globalmeasurements {

    @XmlElement(required = true)
    protected Globalmeasurements.Heartrate heartrate;
    @XmlElement(required = true)
    protected Globalmeasurements.RRint rrint;
    @XmlElement(required = true)
    protected Globalmeasurements.Atrialrate atrialrate;
    @XmlElement(required = true)
    protected Globalmeasurements.Pdur pdur;
    @XmlElement(required = true)
    protected Globalmeasurements.PRint print;
    @XmlElement(required = true)
    protected Globalmeasurements.Qonset qonset;
    @XmlElement(required = true)
    protected Globalmeasurements.QRSdur qrsdur;
    @XmlElement(required = true)
    protected Globalmeasurements.QTint qtint;
    @XmlElement(required = true)
    protected Globalmeasurements.QTcb qtcb;
    @XmlElement(required = true)
    protected Globalmeasurements.QTcf qtcf;
    @XmlElement(required = true)
    protected Globalmeasurements.Pfrontaxis pfrontaxis;
    @XmlElement(name = "i40frontaxis", required = true)
    protected Globalmeasurements.I40Frontaxis i40frontaxis;
    @XmlElement(name = "t40frontaxis", required = true)
    protected Globalmeasurements.T40Frontaxis t40frontaxis;
    @XmlElement(required = true)
    protected Globalmeasurements.Qrsfrontaxis qrsfrontaxis;
    @XmlElement(required = true)
    protected Globalmeasurements.Stfrontaxis stfrontaxis;
    @XmlElement(required = true)
    protected Globalmeasurements.Tfrontaxis tfrontaxis;
    @XmlElement(required = true)
    protected Globalmeasurements.Phorizaxis phorizaxis;
    @XmlElement(name = "i40horizaxis", required = true)
    protected Globalmeasurements.I40Horizaxis i40horizaxis;
    @XmlElement(name = "t40horizaxis", required = true)
    protected Globalmeasurements.T40Horizaxis t40horizaxis;
    @XmlElement(required = true)
    protected Globalmeasurements.Qrshorizaxis qrshorizaxis;
    @XmlElement(required = true)
    protected Globalmeasurements.Sthorizaxis sthorizaxis;
    @XmlElement(required = true)
    protected Globalmeasurements.Thorizaxis thorizaxis;
    @XmlAttribute(name = "editedflag", required = true)
    protected TYPEflag editedflag;

    /**
     * Gets the value of the heartrate property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Heartrate }
     *     
     */
    public Globalmeasurements.Heartrate getHeartrate() {
        return heartrate;
    }
    public Globalmeasurements.RRint getRRint() {
        return rrint;
    }
    public Globalmeasurements.PRint getPRint() {
        return print;
    }
    public Globalmeasurements.QRSdur getQRSduration() {
        return qrsdur;
    }
    public Globalmeasurements.QTint getQTint() {
        return qtint;
    }
    public Globalmeasurements.QTcb getQTCB() {
        return qtcb;
    }
    public Globalmeasurements.QTcf getQTCF() {
        return qtcf;
    }

    /**
     * Sets the value of the heartrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Heartrate }
     *     
     */
    public void setHeartrate(Globalmeasurements.Heartrate value) {
        this.heartrate = value;
    }

    /**
     * Gets the value of the pfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Pfrontaxis }
     *     
     */
    public Globalmeasurements.Pfrontaxis getPfrontaxis() {
        return pfrontaxis;
    }

    /**
     * Sets the value of the pfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Pfrontaxis }
     *     
     */
    public void setPfrontaxis(Globalmeasurements.Pfrontaxis value) {
        this.pfrontaxis = value;
    }

    /**
     * Gets the value of the i40Frontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.I40Frontaxis }
     *     
     */
    public Globalmeasurements.I40Frontaxis getI40Frontaxis() {
        return i40frontaxis;
    }

    /**
     * Sets the value of the i40Frontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.I40Frontaxis }
     *     
     */
    public void setI40Frontaxis(Globalmeasurements.I40Frontaxis value) {
        this.i40frontaxis = value;
    }

    /**
     * Gets the value of the t40Frontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.T40Frontaxis }
     *     
     */
    public Globalmeasurements.T40Frontaxis getT40Frontaxis() {
        return t40frontaxis;
    }

    /**
     * Sets the value of the t40Frontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.T40Frontaxis }
     *     
     */
    public void setT40Frontaxis(Globalmeasurements.T40Frontaxis value) {
        this.t40frontaxis = value;
    }

    /**
     * Gets the value of the qrsfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Qrsfrontaxis }
     *     
     */
    public Globalmeasurements.Qrsfrontaxis getQrsfrontaxis() {
        return qrsfrontaxis;
    }

    /**
     * Sets the value of the qrsfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Qrsfrontaxis }
     *     
     */
    public void setQrsfrontaxis(Globalmeasurements.Qrsfrontaxis value) {
        this.qrsfrontaxis = value;
    }

    /**
     * Gets the value of the stfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Stfrontaxis }
     *     
     */
    public Globalmeasurements.Stfrontaxis getStfrontaxis() {
        return stfrontaxis;
    }

    /**
     * Sets the value of the stfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Stfrontaxis }
     *     
     */
    public void setStfrontaxis(Globalmeasurements.Stfrontaxis value) {
        this.stfrontaxis = value;
    }

    /**
     * Gets the value of the tfrontaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Tfrontaxis }
     *     
     */
    public Globalmeasurements.Tfrontaxis getTfrontaxis() {
        return tfrontaxis;
    }

    /**
     * Sets the value of the tfrontaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Tfrontaxis }
     *     
     */
    public void setTfrontaxis(Globalmeasurements.Tfrontaxis value) {
        this.tfrontaxis = value;
    }

    /**
     * Gets the value of the phorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Phorizaxis }
     *     
     */
    public Globalmeasurements.Phorizaxis getPhorizaxis() {
        return phorizaxis;
    }

    /**
     * Sets the value of the phorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Phorizaxis }
     *     
     */
    public void setPhorizaxis(Globalmeasurements.Phorizaxis value) {
        this.phorizaxis = value;
    }

    /**
     * Gets the value of the i40Horizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.I40Horizaxis }
     *     
     */
    public Globalmeasurements.I40Horizaxis getI40Horizaxis() {
        return i40horizaxis;
    }

    /**
     * Sets the value of the i40Horizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.I40Horizaxis }
     *     
     */
    public void setI40Horizaxis(Globalmeasurements.I40Horizaxis value) {
        this.i40horizaxis = value;
    }

    /**
     * Gets the value of the t40Horizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.T40Horizaxis }
     *     
     */
    public Globalmeasurements.T40Horizaxis getT40Horizaxis() {
        return t40horizaxis;
    }

    /**
     * Sets the value of the t40Horizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.T40Horizaxis }
     *     
     */
    public void setT40Horizaxis(Globalmeasurements.T40Horizaxis value) {
        this.t40horizaxis = value;
    }

    /**
     * Gets the value of the qrshorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Qrshorizaxis }
     *     
     */
    public Globalmeasurements.Qrshorizaxis getQrshorizaxis() {
        return qrshorizaxis;
    }

    /**
     * Sets the value of the qrshorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Qrshorizaxis }
     *     
     */
    public void setQrshorizaxis(Globalmeasurements.Qrshorizaxis value) {
        this.qrshorizaxis = value;
    }

    /**
     * Gets the value of the sthorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Sthorizaxis }
     *     
     */
    public Globalmeasurements.Sthorizaxis getSthorizaxis() {
        return sthorizaxis;
    }

    /**
     * Sets the value of the sthorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Sthorizaxis }
     *     
     */
    public void setSthorizaxis(Globalmeasurements.Sthorizaxis value) {
        this.sthorizaxis = value;
    }

    /**
     * Gets the value of the thorizaxis property.
     * 
     * @return
     *     possible object is
     *     {@link Globalmeasurements.Thorizaxis }
     *     
     */
    public Globalmeasurements.Thorizaxis getThorizaxis() {
        return thorizaxis;
    }

    /**
     * Sets the value of the thorizaxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Globalmeasurements.Thorizaxis }
     *     
     */
    public void setThorizaxis(Globalmeasurements.Thorizaxis value) {
        this.thorizaxis = value;
    }

    /**
     * Gets the value of the editedflag property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEflag }
     *     
     */
    public TYPEflag getEditedflag() {
        return editedflag;
    }

    /**
     * Sets the value of the editedflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEflag }
     *     
     */
    public void setEditedflag(TYPEflag value) {
        this.editedflag = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPErate">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Heartrate {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class RRint {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Atrialrate {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Pdur {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PRint {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Qonset {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class QRSdur {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class QTint {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class QTcb {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEduration">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class QTcf {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class I40Frontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class I40Horizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Pfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Phorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Qrsfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Qrshorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Stfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Sthorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class T40Frontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class T40Horizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Tfrontaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www3.medical.philips.com>TYPEaxis">
     *       &lt;attribute name="editedflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Thorizaxis {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "editedflag")
        protected TYPEflag editedflag;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the editedflag property.
         * 
         * @return
         *     possible object is
         *     {@link TYPEflag }
         *     
         */
        public TYPEflag getEditedflag() {
            if (editedflag == null) {
                return TYPEflag.FALSE;
            } else {
                return editedflag;
            }
        }

        /**
         * Sets the value of the editedflag property.
         * 
         * @param value
         *     allowed object is
         *     {@link TYPEflag }
         *     
         */
        public void setEditedflag(TYPEflag value) {
            this.editedflag = value;
        }

    }

}
