//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.09 at 03:53:07 PM EST 
//


package parser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="compressflag" use="required" type="{http://www3.medical.philips.com}TYPEflag" />
 *       &lt;attribute name="compressmethod" use="required" type="{http://www3.medical.philips.com}TYPEcompress" />
 *       &lt;attribute name="filterflag" type="{http://www3.medical.philips.com}TYPEflag" default="False" />
 *       &lt;attribute name="dataencoding" use="required" type="{http://www3.medical.philips.com}TYPEdataencoding" />
 *       &lt;attribute name="durationperchannel" use="required" type="{http://www3.medical.philips.com}TYPEduration" />
 *       &lt;attribute name="nbitspersample" use="required" type="{http://www3.medical.philips.com}TYPEnbitspersample" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "parsedwaveforms")
public class Parsedwaveforms {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "dataencoding", required = true)
    protected TYPEdataencoding dataencoding;
    @XmlAttribute(name = "compression", required = true)
    protected String compression;
    @XmlAttribute(name = "numberofleads", required = true)
    protected String numberofleads;
    @XmlAttribute(name = "leadlabels", required = true)
    protected String leadlabels;
    @XmlAttribute(name = "durationperchannel", required = true)
    protected String durationperchannel;
    @XmlAttribute(name = "samplespersecond", required = true)
    protected String samplespersecond;
    @XmlAttribute(name = "resolution", required = true)
    protected String resolution;
    @XmlAttribute(name = "signaloffset", required = true)
    protected String signaloffset;
    @XmlAttribute(name = "signalsigned", required = true)
    protected String signalsigned;
    @XmlAttribute(name = "bitspersample", required = true)
    protected String bitspersample;
    @XmlAttribute(name = "hipass", required = true)
    protected String hipass;
    @XmlAttribute(name = "lowpass", required = true)
    protected String lowpass;
    @XmlAttribute(name = "notchfiltered", required = true)
    protected String notchfiltered;
    @XmlAttribute(name = "notchfilterfreqs", required = true)
    protected String notchfilterfreqs;
    @XmlAttribute(name = "donotfilter", required = true)
    protected String donotfilter;
            /*
    @XmlAttribute(name = "compressflag", required = true)
    protected TYPEflag compressflag;
    @XmlAttribute(name = "compressmethod", required = true)
    protected TYPEcompress compressmethod;
    @XmlAttribute(name = "filterflag")
    protected TYPEflag filterflag;
    @XmlAttribute(name = "dataencoding", required = true)
    protected TYPEdataencoding dataencoding;
    @XmlAttribute(name = "durationperchannel", required = true)
    protected String durationperchannel;
    @XmlAttribute(name = "nbitspersample", required = true)
    protected int nbitspersample;
*/
    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the dataencoding property.
     * 
     * @return
     *     possible object is
     *     {@link TYPEdataencoding }
     *     
     */
    public TYPEdataencoding getDataencoding() {
        return dataencoding;
    }

    /**
     * Sets the value of the dataencoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYPEdataencoding }
     *     
     */
    public void setDataencoding(TYPEdataencoding value) {
        this.dataencoding = value;
    }

        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompression() {
        return compression;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompression(String value) {
        this.compression = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberofleads() {
        return numberofleads;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberofleads(String value) {
        this.numberofleads = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadlabels() {
        return leadlabels;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadlabels(String value) {
        this.leadlabels = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationperchannel() {
        return durationperchannel;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationperchannel(String value) {
        this.durationperchannel = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplespersecondValue() {
        return samplespersecond;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplespersecond(String value) {
        this.samplespersecond = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolution(String value) {
        this.resolution = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignaloffsetValue() {
        return signaloffset;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignaloffset(String value) {
        this.signaloffset = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalsigned() {
        return signalsigned;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalsigned(String value) {
        this.signalsigned = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBitspersample() {
        return bitspersample;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBitspersample(String value) {
        this.bitspersample = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHipass() {
        return hipass;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHipass(String value) {
        this.hipass = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLowpass() {
        return lowpass;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLowpass(String value) {
        this.lowpass = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotchfiltered() {
        return notchfiltered;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotchfiltered(String value) {
        this.notchfiltered = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotchfilterfreqs() {
        return notchfilterfreqs;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotchfilterfreqs(String value) {
        this.notchfilterfreqs = value;
    }
    
        /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDonotfilter() {
        return donotfilter;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDonotfilter(String value) {
        this.donotfilter = value;
    }

}
