//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.09 at 03:53:07 PM EST 
//


package parser;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www3.medical.philips.com}pdur"/>
 *         &lt;element ref="{http://www3.medical.philips.com}print"/>
 *         &lt;element ref="{http://www3.medical.philips.com}qonset"/>
 *         &lt;element ref="{http://www3.medical.philips.com}qrsdur"/>
 *         &lt;element ref="{http://www3.medical.philips.com}tonset"/>
 *         &lt;element ref="{http://www3.medical.philips.com}qtint"/>
 *         &lt;element ref="{http://www3.medical.philips.com}waveform"/>
 *       &lt;/sequence>
 *       &lt;attribute name="leadname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pdur",
    "print",
    "qonset",
    "qrsdur",
    "tonset",
    "qtint",
    "waveform"
})
@XmlRootElement(name = "repbeat")
public class Repbeat {

    @XmlAttribute(name = "leadname", required = true)
    protected String leadname;
    @XmlElement(required = true)
    protected String pdur;
    @XmlElement(required = true)
    protected String print;
    @XmlElement(required = true)
    protected String qonset;
    @XmlElement(required = true)
    protected String qrsdur;
    @XmlElement(required = true)
    protected String tonset;
    @XmlElement(required = true)
    protected String qtint;
    @XmlElement(required = true)
    protected Waveform waveform;

    /**
     * Gets the value of the pdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdur() {
        return pdur;
    }

    /**
     * Sets the value of the pdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdur(String value) {
        this.pdur = value;
    }

    /**
     * Gets the value of the print property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrint() {
        return print;
    }

    /**
     * Sets the value of the print property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrint(String value) {
        this.print = value;
    }
    
    /**
     * Gets the value of the qonset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQonset() {
        return qonset;
    }

    /**
     * Sets the value of the qonset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQonset(String value) {
        this.qonset = value;
    }
    
    /**
     * Gets the value of the qrsdur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrsdur() {
        return qrsdur;
    }

    /**
     * Sets the value of the qrsdur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrsdur(String value) {
        this.qrsdur = value;
    }

    /**
     * Gets the value of the tonset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTonset() {
        return tonset;
    }

    /**
     * Sets the value of the tonset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTonset(String value) {
        this.tonset = value;
    }

    /**
     * Gets the value of the qtint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtint() {
        return qtint;
    }

    /**
     * Sets the value of the qtint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtint(String value) {
        this.qtint = value;
    }

    /**
     * Gets the value of the waveform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Waveform getWaveform() {
        return waveform;
    }

    /**
     * Sets the value of the waveform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaveform(Waveform value) {
        this.waveform = value;
    }

}
