//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.09 at 03:53:07 PM EST 
//


package parser;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TYPEleadset.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TYPEleadset">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="STD-3"/>
 *     &lt;enumeration value="STD-4"/>
 *     &lt;enumeration value="STD-5"/>
 *     &lt;enumeration value="MCL-5"/>
 *     &lt;enumeration value="STD-12"/>
 *     &lt;enumeration value="STD-12 MASON-LIKAR"/>
 *     &lt;enumeration value="MIDA"/>
 *     &lt;enumeration value="EASI"/>
 *     &lt;enumeration value="EASI ON STERNUM STANDARD"/>
 *     &lt;enumeration value="EASI ON STERNUM MASON-LIKAR"/>
 *     &lt;enumeration value="EASI OFF STERNUM STANDARD"/>
 *     &lt;enumeration value="EASI OFF STERNUM MASON-LIKAR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TYPEleadset")
@XmlEnum
public enum TYPEleadset {

    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("STD")
    STD("STD"),
    @XmlEnumValue("STD 12+")
    STD_12_PLUS("STD 12+"),
    @XmlEnumValue("MASON-LIKAR")
    MASON_LIKAR("MASON-LIKAR"),
    @XmlEnumValue("MASON-LIKAR 12+")
    MASON_LIKAR_12_PLUS("MASON-LIKAR 12+"),
    @XmlEnumValue("MODIFIED")
    MODIFIED("MODIFIED"),
    @XmlEnumValue("MODIFIED 12+")
    MODIFIED_12_PLUS("MODIFIED 12+"),
    MIDA("MIDA"),
    EASI("EASI"),
    @XmlEnumValue("EASI OFF STERNUM")
    EASI_OFF_STERNUM("EASI OFF STERNUM"),
    @XmlEnumValue("FRANK")
    FRANK("FRANK"),
    @XmlEnumValue("NEHB")
    NEHB("NEHB"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    TYPEleadset(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TYPEleadset fromValue(String v) {
        for (TYPEleadset c: TYPEleadset.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
